import { Button, VerticalBox, ListView } from "std-widgets.slint";

struct Line {
	text: string,
	has-command: bool,
	is-title: bool,
	is-warning: bool,
}

component Warning inherits Text {
    font-weight: 700;
	text: "warning ";
	color: orangered;
}

component ViewLine inherits Text {
	in property <bool> has-command;
	in property <bool> is-title;

	property <bool> should-react: self.has-command && self.text != "" && !self.is-title;

	callback clicked();

	font-weight: self.is-title ? 750 : area.has-hover && self.should-react ? 700 : 500;

	area := TouchArea {
		mouse-cursor: root.should-react ? MouseCursor.pointer : MouseCursor.default;
		clicked => {
			if (root.should-react) {
				root.clicked();
			}
		}
	}
}

export component AppWindow inherits Window {
	in property<[Line]> lines: [];
	in property<string> view-title;

	callback line-clicked(int);

	min-width: 300px;
	min-height: 500px;

	VerticalBox {
		Text {
			text: view-title;
		}
		ListView {
			for line[i] in lines : HorizontalLayout {
				alignment: start;
				if line.is-warning : Warning {}
				ViewLine {
					text: line.text;
					has-command: line.has-command;
					is-title: line.is-title;

					clicked => {
						root.line-clicked(i);
					}
				}
			}
		}
	}
}
