import { Button, VerticalBox, ListView } from "std-widgets.slint";

struct Line {
	text: string,
	has-command: bool,
}

component ViewLine inherits Text {
	in property <bool> has-command;

	property <bool> should-react: self.has-command && self.text != "";

	callback clicked();

	font-weight: area.has-hover && self.should-react ? 600 : 400;

	area := TouchArea {
		mouse-cursor: root.should-react ? MouseCursor.pointer : MouseCursor.default;
		clicked => {
			if (root.should-react) {
				root.clicked();
			}
		}
	}
}

export component AppWindow inherits Window {
	in property<[Line]> lines: [];
	in property<string> view-title;

	callback line-clicked(int);

	min-width: 300px;
	min-height: 500px;

	VerticalBox {
		Text {
			text: view-title;
		}
		ListView {
			for line[i] in lines : ViewLine {
				text: line.text;
				has-command: line.has-command;
				clicked => {
					root.line-clicked(i);
				}
			}
		}
	}
}
